# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 5e6a913
_src_path: gh:vivienm/copier-rust
author_fullname: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
copyright_year: 2022
package_name: fontawesome
pages_enabled: true
pages_provider: github.io
pages_url: https://vivienm.github.io/rust-fontawesome
project_description: The Font Awesome icon set for Rust.
project_name: fontawesome
project_type: lib
repository_hosted: true
repository_name: rust-fontawesome
repository_namespace: vivienm
repository_provider: github.com
repository_url: https://github.com/vivienm/rust-fontawesome
rust_toolchain: nightly
