[package]
name = "fontawesome"
version = "0.1.0"
edition = "2018"

[build-dependencies]
anyhow = "1.0.41"
convert_case = "0.4.0"
reqwest = "0.11.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_yaml = "0.8.17"
tera = "1.11.0"
tokio = { version = "1.7.1", features = ["macros"] }
